image: registry.gitlab.com/blurt/build-docker:latest

stages: 
 - build
 - triggers
 - pdfs

before_script: 
# Pull in submodules
  - git submodule update --init --recursive
# ccache for acceleration
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache

# caches ccache for future use 
cache:
  paths:
  - ccache/

debug:
  stage: build 
  script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBLURT_STATIC_BUILD=OFF -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=ON -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=OFF -DCMAKE_BUILD_TYPE=Debug ..
  - make -j$(nproc) blurtd cli_wallet
  artifacts:
    paths:
    - /builds/blurt/blurt/build/programs/blurtd/blurtd
    - /builds/blurt/blurt/build/programs/cli_wallet/cli_wallet

low_memory:
  stage: build 
  script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=ON -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=ON -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc) blurtd cli_wallet
  artifacts:
    paths:
    - /builds/blurt/blurt/build/programs/blurtd/blurtd
    - /builds/blurt/blurt/build/programs/cli_wallet/cli_wallet

rpc:
  stage: build 
  script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=OFF -DCLEAR_VOTES=OFF -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=OFF -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=OFF -DCMAKE_BUILD_TYPE=Release ..
  - make -j$(nproc) blurtd cli_wallet
  artifacts:
    paths:
    - /builds/blurt/blurt/build/programs/blurtd/blurtd
    - /builds/blurt/blurt/build/programs/cli_wallet/cli_wallet

trigger-rosetta:
    stage: triggers
    trigger: blurt/rosetta

trigger-docker:
    stage: triggers
    trigger: blurt/docker



