stages:
  - build
  - docker
  - test
  - pdfs

low_memory:
  image: conanio/clang10
  before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen
    - conan config set storage.path="${CI_PROJECT_DIR}/.cache/conan"
    # Pull in submodules
    - git submodule update --init --recursive
    # ccache for acceleration
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. -s compiler=clang -s compiler.libcxx=libstdc++11 -if=. -pr=default --build=missing
    # Witness Build Config: -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON
    - cmake -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=ON -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=ON -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(nproc) blurtd
  # cli wallet is only used for witness, so we capture it from the witness build
  tags:
    - metal
  artifacts:
    paths:
      - /builds/blurt/blurt/build/bin/blurtd
      - /builds/blurt/blurt/build/bin/cli_wallet


rpc:
  image: conanio/clang10
  before_script:
    - sudo apt-get update -qq
    - sudo apt-get install -qq doxygen
    - conan config set storage.path="${CI_PROJECT_DIR}/.cache/conan"
    # Pull in submodules
    - git submodule update --init --recursive
    # ccache for acceleration
    - mkdir -p ccache
    - export CCACHE_BASEDIR=${PWD}
    - export CCACHE_DIR=${PWD}/ccache
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. -s compiler=clang -s compiler.libcxx=libstdc++11 -if=. -pr=default --build=missing
    - cmake -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=OFF -DCLEAR_VOTES=OFF -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=OFF -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=OFF -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(nproc) blurtd
  tags:
    - metal
  artifacts:
    paths:
      - /builds/blurt/blurt/build/bin/blurtd
      - /builds/blurt/blurt/build/bin/cli_wallet

pdfs:
  image: debian:10
  stage: build
  #makes sure that the document generator does not pick up the cache and do strange things.
  cache: {}
  before_script:
    # Download and install pandoc and kramdown before we begin
    # pandoc does PDF, but requires pdflatex, which can be a ~500mb download
    # so we go for kramdown, which handles PDF, but doesn't handle DOCX
    - apt-get update -y
    - apt-get install -y pandoc texlive-xetex
  script:
    # Runs pandoc on all .md files in the repo and outputs them as PDF and DOCX
    - pandoc doc/witnesses.md --pdf-engine=xelatex --o witnesses.pdf
  artifacts:
    # Attach all untracked files (e.g. files that were recently created and not yet committed to git) as artifacts.
    # These are the files you then download after the job has finished.
    untracked: true
  only:
    changes:
      - doc/witnesses.md
  tags:
      - metal

docker low memory:
  image: docker:latest
  variables:
    DOCKER_TLS_CERTDIR: ""
  services:
    - docker:dind
  stage: docker
  script:
    - pwd
    - ls
    - cd contrib/Dockerfiles/low_memory
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH .
    - docker push registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH
  needs: ["low_memory"]
  tags:
    - metal

docker rpc:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  stage: docker
  script:
    - pwd
    - ls
    - cd contrib/Dockerfiles/rpc
    - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t registry.gitlab.com/blurt/blurt/rpc/$CI_COMMIT_BRANCH .
    - docker push registry.gitlab.com/blurt/blurt/rpc/$CI_COMMIT_BRANCH
  needs: ["rpc"]
  tags:
    - metal

test docker low memory:
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  stage: test
  script:
    - docker run -d registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH  /bin/bash -c "nohup /blurt/build/bin/blurtd --data-dir /blurtd& && sleep 30 && sh contrib/healthcheck.sh"
  needs: ["docker low memory"]
  tags:
    - metal

include:
  local:
    - Tests.gitlab-ci.yml



