version: "3.9"
services:

# the websocket is port 8090 and http is 8091
# the witness image is used here, but you might wish to change it to the rpc image
  blurt:
    image: faddat/blurtrpc-amd64
    ports:
      - 8091:8091
      - 8090:8090
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - blurtd:/blurtd


# Condenser is Blurt's traditional front end.  This compose file will let you swap condenser and optic as optic is being developed. 
  condenser:
    image: registry.gitlab.com/blurt/blurt/condenser:dev
    ports:
      - 8080:8080
    environment:
      - SDC_SESSION_SECRETKEY=oiS1WOqBDeQTw+8lbIX5gJjTZt3qry6yE3obBZf4VXbechihWeMmJhvHzLjWFKfr%
      - SDC_SERVER_BLURTD_URL=http://blurt:8091
    deploy:
      restart_policy:
        condition: on-failure

# Imgproxy is used to resize images.  It is not on the blurt network because the other processes do not interact with it directly.
  imgproxy:
    image: darthsim/imgproxy
    ports: 
      - 8069:8080
    deploy:
      restart_policy:
        condition: on-failure
#    environment:
#      - AWS_ACCESS_KEY_ID=my_access_key
#      - AWS_SECRET_ACCESS_KEY=my_secret_key
#      - IMGPROXY_S3_ENDPOINT=http://minio-address.com


# Your node hosts its own images, as well as images that others host.  Later we will add payments to this, creating a storage use case for BLURT. 
  ipfs:
    image: ipfs/go-ipfs
    deploy:
      restart_policy:
        condition: on-failure
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /root/.ipfs:/config
    ports:
      - 4001:4001
      - 5001:5001
      - 8070:8080


# Caddy is the user-facing http server.  It is configured with the Caddyfile in contrib.  You will want to get your domain name in there.  An example  has been provided.  On the raspberry Pi, this will be http://blurt.local.
  caddy:
    image: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - $PWD/contrib/RPC-Caddyfile:/etc/caddy/Caddyfile



  upload:
     build: storage/imageupload
     ports: 
       - 7070:7070


networks:
  blurt:
  ipfs:

volumes:
  blurtd:

