
version: "3.9"
services:

# the websocket is port 8090 and http is 8091
# the witness image is used here, but you might wish to change it to the rpc image
  blurt:
    image: faddat/blurtrpc-amd64
    ports:
      - "8091:8091"
      - "8090:8090"
    networks:
      - blurt
    deploy:
      restart_policy:
        condition: unless-stopped
    volumes:
      - blurtd:/blurtd

  condenser:
    image: gitlab.com/blurt/blurt/condenser:dev
    ports:
      - 8080:8080
    networks:
      - blurt

# Imgproxy is used to resize images.  It is not on the blurt network because the other processes do not interact with it directly.
  imgproxy:
    image: darthsim/imgproxy
    ports: 8069:8080


  ipfs:
    image: ipfs/go-ipfs
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /root/.ipfs:/config
    ports:
      - 4001:4001
      - 5001:5001
      - 8070:8080


# Caddy is the user-facing http server.  It is configured with the Caddyfile in contrib.  You will want to get your domain name in there.  An example  has been provided.  
  caddy:
    image: caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv




networks:
  blurt:



