image: conanio/gcc9

cache:
  paths:
    - .cache/conan
    # ccache doesnt work
    - ccache


before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -qq doxygen
  - conan config set storage.path="${CI_PROJECT_DIR}/.cache/conan"
  # Pull in submodules
  - git submodule update --init --recursive
  # ccache for acceleration
  - mkdir -p ccache
  - export CCACHE_BASEDIR=${PWD}
  - export CCACHE_DIR=${PWD}/ccache


gcc9_debug:
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11 -if=. -pr=default --build=missing
    # Debug Build Config: (Note: DCMAKE_BUILD_TYPE=Debug)
    - cmake -DBLURT_STATIC_BUILD=OFF -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=ON -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=OFF -DCMAKE_BUILD_TYPE=Debug ..
    - make -j$(nproc) blurtd
    # Fix recovery of artifacts :/
    - pwd
  tags:
    - metal



gcc9_low_memory:
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11 -if=. -pr=default --build=missing
    # Witness Build Config: -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON
    - cmake -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=ON -DCLEAR_VOTES=ON -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=ON -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=ON -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(nproc) blurtd cli_wallet
  # cli wallet is only used for witness, so we capture it from the witness build
  tags:
    - metal


gcc9_rpc:
  stage: build
  script:
    - mkdir build
    - cd build
    - conan install .. -s compiler=gcc -s compiler.libcxx=libstdc++11 -if=. -pr=default --build=missing
    # Full Node Build Configuration -DLOW_MEMORY_NODE=OFF -DCLEAR_VOTES=OFF
    - cmake -DBLURT_STATIC_BUILD=ON -DLOW_MEMORY_NODE=OFF -DCLEAR_VOTES=OFF -DBUILD_BLURT_TESTNET=OFF -DSKIP_BY_TX_ID=OFF -DBLURT_LINT_LEVEL=OFF -DENABLE_MIRA=OFF -DCMAKE_BUILD_TYPE=Release ..
    - make -j$(nproc) blurtd
  tags:
    - metal
  artifacts:
    paths:
      - /builds/blurt/blurt/build/programs/blurtd/blurtd

