staging low memory:
  stage: staging
  image: $CI_REGISTRY_IMAGE/low_memory:$CI_COMMIT_BRANCH
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.blurtwallet.com
  tags:
    - kubernetes
  needs: ["kaniko low memory"]
  when: manual


staging rpc:
  stage: staging
  image: $CI_REGISTRY_IMAGE/rpc:$CI_COMMIT_BRANCH
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.blurtwallet.com
  tags:
    - kubernetes
  needs: ["kaniko rpc"]
  when: manual
