low_memory_staging:
  stage: staging
  image: registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: stop_review
  tags:
    - kubernetes


stop_low_memory_staging:
  stage: staging
  variables:
    GIT_STRATEGY: none
  script:
    - exit
  when: manual
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  tags:
    - kubernetes