staging low memory:
  stage: staging
  image: registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH
  script:
    - /blurt/build/bin/blurtd --data-dir /blurtd
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.blurtwallet.com
  tags:
    - kubernetes
  needs: ["docker low memory"]


staging rpc:
  stage: staging
  image: registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH
  script:
    - /blurt/build/bin/blurtd --data-dir /blurtd
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.blurtwallet.com
  tags:
    - kubernetes
  needs: ["docker rpc"]

staging rosetta:
  stage: staging
  image: registry.gitlab.com/blurt/blurt/rosetta/$CI_COMMIT_BRANCH
  script:
    - /blurt/build/bin/blurtd --data-dir /blurtd
  environment:
    name: rosetta_stagings
