staging low memory:
  stage: staging
  image: registry.gitlab.com/blurt/blurt/low_memory/$CI_COMMIT_BRANCH
  script:
    - ""
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://$CI_ENVIRONMENT_SLUG.example.com
    on_stop: stop_review
  tags:
    - kubernetes
