version: "3.7"
services:
    blurt_wallet:
        build:
            context: .
            target: development
        container_name: wallet
        ports:
            - 80:8080
            - 8080:8080
        environment:
            SDC_CLIENT_BLURTD_URL: https://api.blurt.blog
            SDC_SERVER_BLURTD_URL: https://api.blurt.blog
            SDC_DISABLE_SIGNUPS: 1

            # add to your /etc/hosts
            # 127.0.0.1     blurtblog.local
            SDC_SITE_DOMAIN: blurtblog.local

            SDC_IMAGE_PROXY_PREFIX: https://images.blurt.blog/
            SDC_UPLOAD_IMAGE_URL: https://images.blurt.blog
            SDC_HELMET_CONNECTSRC: "'self' http://blurtblog.local https://blurt.world https://images.blurt.blog https://api.blurt.blog https://rpc.blurt.world https://blurtd.privex.io https://imgp.blurt.world"
        volumes:
            - ./yarn.lock:/var/app/yarn.lock
            - ./package.json:/var/app/package.json
            - ./src:/var/app/src:delegated
            - ./webpack:/var/app/webpack:delegated
            - ./config:/var/app/config:delegated
